### ISSUE TITLE
Search

### ISSUE THREAD

**Issue by MStojkovic** [MStojkovic/dudusgram#9]
Search is only an exact match.

**Comment by MStojkovic** [comment]
Try this to upgrade it a little bit: https://stackoverflow.com/questions/38618953/how-to-do-a-simple-search-in-string-in-firebase-database/40633692

**Comment by DinoJukic** [comment]
The suggested method seems to work, however:
-if the user types in the exact username the query will return the same user twice.
-after that if the user presses backspace and holds it until the string is empty the query will return several copies of the same user as well as any matching string. This bug is fixed if the user presses backspace once more while the search string is empty.
-pressing backspace every time (not holding) will refresh and result in the correct output

NOTE:  no changes have been commited, only locally, but the changes were canceled to match last commit.

**Comment by marin117** [comment]
Following bugs look resolvable with couple of workarounds.

- I think that you can populate list with only unique users (I believe that there is a method upon Array/List in Java which returns only unique values) - if I understood first issue correctly, this can be done after retrieving users from firebase

- If I am correct, second and third issue can be resolved by overriding EditText methods, and I believe that third issue is not even an issue (same thing happens on Instagram too) 

Note: For situations like this create separate branch from master and push the code on the branch so the code can be reviewed. Following [tutorial](https://git-scm.com/book/en/v2/Git-Branching-Basic-Branching-and-Merging) will help you to understand git branches.

**Comment by MStojkovic** [comment]
Fixed in: 1391ca63b19fc8454154631360fc091654dd03b8.
Thanks to @marin117 for his help.
